version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.3-bionic
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: klxs8cj3zkl2dsnzg89fklza
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Amsterdam"

  webserver:
    image: engency/webserver:debug-webserver-npm
    entrypoint: ./scripts/startup.sh
    volumes:
      - .:/var/www/html
      - ./storage/apache:/var/log/apache2
    ports:
      - "80:80"
    environment:
      CONTAINER_ROLE: app
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=webserver
      TZ: "Europe/Amsterdam"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s

  queue:
    image: engency/webserver:debug-webserver
    entrypoint: ./scripts/startup.sh
    user: www-data
    volumes:
      - .:/var/www/html
    depends_on:
      - webserver
    environment:
      CONTAINER_ROLE: queue
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=queue
      TZ: "Europe/Amsterdam"
