version: '3'

services:
  phpunit_mariadb:
    image: mariadb:10.5.3-bionic
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: klxs8cj3zkl2dsnzg89fklza
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Amsterdam"

  phpunit_webserver:
    image: engency/webserver:debug-webserver-npm
    entrypoint: ./scripts/startup.sh
    volumes:
      - .:/var/www/html
      - ./storage_template:/var/www/html/storage
      - ./docker/webserver/logs:/var/log/apache2
    ports:
      - "80:80"
    environment:
      CONTAINER_ROLE: app
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=webserver
      TZ: "Europe/Amsterdam"
